// <auto-generated />
using System;
using AIPersonalAssistant.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIPersonalAssistant.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260915051142_UserReflection")]
    partial class UserReflection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("AIPersonalAssistant.Models.AIFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AIFeatures");
                });

            modelBuilder.Entity("AIPersonalAssistant.Models.AIMemory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EvidenceCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstObservedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastObservedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MemoryType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Key");

                    b.HasIndex("UserId", "Status");

                    b.HasIndex("UserId", "Subject");

                    b.ToTable("AIMemories", (string)null);
                });

            modelBuilder.Entity("AIPersonalAssistant.Models.AIMemoryObservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AIMemoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservationValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AIMemoryId");

                    b.HasIndex("UserId");

                    b.ToTable("AIMemoryObservations", (string)null);
                });

            modelBuilder.Entity("AIPersonalAssistant.Models.AIRecap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionableInsights")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EmailSendAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEmailSent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PositiveAffirmations")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SummaryText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AIRecaps");
                });

            modelBuilder.Entity("AIPersonalAssistant.Models.ActivityLogs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsReminder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OriginalReminderTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReminderTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("RescheduleCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResolutionSource")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("AIPersonalAssistant.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "syahrul.mubarrok4@gmail.com",
                            FullName = "Initial Admin",
                            IsApproved = true,
                            PasswordHash = "$2a$11$6oxMfDVwCeUxiPzw0757d.3eDNJ6j4mCPMbiRxfV.kDsQdnrqD5dG",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("AIPersonalAssistant.Models.UserAIFeature", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FeatureId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "FeatureId");

                    b.HasIndex("FeatureId");

                    b.ToTable("UserAIFeatures");
                });

            modelBuilder.Entity("AIPersonalAssistant.Models.UserReflection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AIFeedback")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContextType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessedActionsJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VoiceTranscript")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserReflections");
                });

            modelBuilder.Entity("AIPersonalAssistant.Models.AIMemory", b =>
                {
                    b.HasOne("AIPersonalAssistant.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("AIPersonalAssistant.Models.AIMemoryObservation", b =>
                {
                    b.HasOne("AIPersonalAssistant.Models.AIMemory", "AIMemory")
                        .WithMany("Observations")
                        .HasForeignKey("AIMemoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIPersonalAssistant.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AIMemory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AIPersonalAssistant.Models.AIRecap", b =>
                {
                    b.HasOne("AIPersonalAssistant.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AIPersonalAssistant.Models.ActivityLogs", b =>
                {
                    b.HasOne("AIPersonalAssistant.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AIPersonalAssistant.Models.UserAIFeature", b =>
                {
                    b.HasOne("AIPersonalAssistant.Models.AIFeature", "AIFeature")
                        .WithMany("UserAIFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIPersonalAssistant.Models.User", "User")
                        .WithMany("UserAIFeatures")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AIFeature");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AIPersonalAssistant.Models.UserReflection", b =>
                {
                    b.HasOne("AIPersonalAssistant.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AIPersonalAssistant.Models.AIFeature", b =>
                {
                    b.Navigation("UserAIFeatures");
                });

            modelBuilder.Entity("AIPersonalAssistant.Models.AIMemory", b =>
                {
                    b.Navigation("Observations");
                });

            modelBuilder.Entity("AIPersonalAssistant.Models.User", b =>
                {
                    b.Navigation("UserAIFeatures");
                });
#pragma warning restore 612, 618
        }
    }
}
